import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Sidebar from '../../components/Sidebar'
import { Client } from '@notionhq/client'
import { SidebarContext } from '../../global-state/SidebarContext'
import { fetchSidebarOptions } from '../../notion-api/sidebar'
import { useContext, useEffect, useState } from 'react'

import { NotionRenderer, Code, Collection, CollectionRow } from 'react-notion-x'
import { NotionAPI } from 'notion-client'

export const getStaticProps = async () => {
  // TODO: write a function to consolidate notionApi creation
  const notion = new Client({ auth: process.env.NOTION_KEY })
  const notionApi = new NotionAPI({
    authToken: process.env.APP_TOKEN,
    activeUser: process.env.NOTION_USER_ID
  })

  const sidebarOptions = await fetchSidebarOptions(notion, process.env.PORTFOLIO_HUB_PAGE_ID)

  const writingPageData = await notionApi.getPage(process.env.WRITING_PAGE_ID)

  return {
    props: {
      sidebarOptions,
      writingPageData
    }
  }
}

/*
  TODO: componentize the page!
*/
const Writing = ({
  sidebarOptions,
  writingPageData
}) => {
  const { setSidebarOptions } = useContext(SidebarContext)
  const [writingPage, setWritingPage] = useState(undefined)

  useEffect(() => {
    setSidebarOptions(sidebarOptions)
  }, [sidebarOptions, setSidebarOptions])

  useEffect(() => {
    console.log('w', writingPageData)
    setWritingPage(writingPageData)
  }, [writingPageData])

  useEffect(() => {

  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      {writingPage && 
        <NotionRenderer
          recordMap={writingPage}
          fullPage={true}
          components={{
            code: Code,
            collection: Collection,
            collectionRow: CollectionRow
          }}
        />
      }
    </div>
  )
}

export default Writing
