// import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Sidebar from '../../components/Sidebar'
import { Client } from '@notionhq/client'
import { SidebarContext, fetchSidebarOptions } from '../../globalState/SidebarContext'
import { useContext, useEffect } from 'react'

/*
  TODO: fetch all the data from the writing page here
    * all blocks
    * then, get the data inside the database
    * look at the separation of responsibilities in https://github.com/vercel/next-learn/blob/master/basics/demo/pages/posts/%5Bid%5D.js
*/
export const getStaticProps = async () => {
  const notion = new Client({ auth: process.env.NOTION_KEY })

  const sidebarOptions = await fetchSidebarOptions(notion, process.env.PORTFOLIO_HUB_PAGE_ID)

  return {
    props: {
      sidebarOptions
    }
  }
}

const Writing = ({ sidebarOptions }) => {
  const { setSidebarOptions } = useContext(SidebarContext)

  useEffect(() => {
    setSidebarOptions(sidebarOptions)
  }, [sidebarOptions, setSidebarOptions])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world! this is the writing page of my portfolio site!</h1>
      <Sidebar />
    </div>
  )
}

export default Writing
