// core react + next imports
import React, { Fragment } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'

// react-notion-x core components
import {
  NotionRenderer, Code, Collection, CollectionRow, Equation
} from 'react-notion-x'

// other libs
import TweetEmbed from 'react-tweet-embed'
import HashLoader from 'react-spinners/HashLoader'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowLeftLong } from '@fortawesome/free-solid-svg-icons'

// functions
import { getCanonicalPageUrl, mapPageUrl } from '../lib/map-page-url'

// components
import { BackArrowContainer, CenteredContainer } from '../styles/containers'
import Menu from './Menu'
import { siteLinks } from './Links'

const Page = ({
  headTitle,
  rootPath,
  page: { site, pageId, recordMap, error },
  parent,
  backArrow,
  additionalContent
}) => {
  // TODO: figure out whether or not this can be removed from page
  // ! ^ might be a styling issue when this removed + just on index.js
  const router = useRouter()
  if (router.isFallback) return (
    <CenteredContainer>
      <HashLoader />
    </CenteredContainer>
  )

  const siteMapPageUrl = mapPageUrl(site, recordMap, new URLSearchParams(), pageId)

  const canonicalPageUrl = process.env.NODE_ENV !== 'development'
    && getCanonicalPageUrl(site, recordMap)(pageId)

  return (
    <Fragment>
      <Head>
        <title>{headTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {canonicalPageUrl && (
          <>
            <link rel='canonical' href={canonicalPageUrl} />
            <meta property='og:url' content={canonicalPageUrl} />
            <meta property='twitter:url' content={canonicalPageUrl} />
          </>
        )}
      </Head>
      {backArrow &&
        <BackArrowContainer className='back-arrow-container'>
          {siteLinks.filter(link => link.name === parent.toLowerCase())
            .map(item =>
              <Link href={item.href} passHref>
                <span className="link">
                  <FontAwesomeIcon icon={faArrowLeftLong} />{item.icon}&nbsp;{parent}
                </span>
              </Link>
            )}
        </BackArrowContainer>
      }
      <NotionRenderer
        recordMap={recordMap}
        fullPage={true}
        mapPageUrl={siteMapPageUrl}
        components={{
          pageLink: ({
            href,
            as,
            passHref,
            prefetch,
            replace,
            scroll,
            shallow,
            locale,
            ...props
          }) => {
            /*
              * for supported collections, remaps collection item hrefs to url property
              * right now, only supports media reading table as a hackaround to get
              * the entire row to link out to article onhover / onclick
            */
            if (props.className.includes('notion-page-link') && headTitle === 'Media') {
              let properties

              if (props.className === 'notion-list-item notion-page-link') {
                properties = props.children[0].props.children.props.block.properties
              } else properties = props.children.props.block.properties

              const newHref = properties['2507ec7d-729d-47ec-b210-c62e3c406a7d'][0][0]

              return <a href={newHref} target="_blank" rel="noreferrer" {...props} />
            }

            return (
              <Link
                href={`${rootPath || ''}${href}`}
                as={as}
                passHref={passHref}
                prefetch={prefetch}
                replace={replace}
                scroll={scroll}
                shallow={shallow}
                locale={locale}
              >
                <a {...props} />
              </Link>
            )
          },
          code: Code,
          tweet: ({ id }) => (
            <TweetEmbed tweetId={id} />
          ),
          collection: Collection,
          collectionRow: CollectionRow,
          equation: Equation
        }}
      />
      {additionalContent}
      <Menu />
    </Fragment>
  )
}

export default Page
