// import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar'
import { Client } from '@notionhq/client'
import { SidebarContext } from '../globalState/SidebarContext'
import { useContext, useEffect } from 'react'

/*
  TODO: split logic into separate functions:
    * fetch all the sidebar options in one function -> this will require multiple API calls
    * fetch the homepage data to render it below!
  
  TODO: convert this component to TypeScript once I feel comfortable with types + fetching + rendering
*/
export const getStaticProps = async () => {
  const notion = new Client({ auth: process.env.NOTION_KEY })
  const pageId = process.env.PORTFOLIO_HUB_PAGE_ID
  const options = await notion.blocks.children.list({ block_id: pageId })

  return { props: { options } }
}

const Home = ({ options }) => {
  const { setSidebarOptions } = useContext(SidebarContext)

  useEffect(() => {
    setSidebarOptions(options)
  }, [options, setSidebarOptions])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world! this is my portfolio site!</h1>
      <Sidebar />
    </div>
  )
}

export default Home
